### ISSUE TITLE
[Bug] False-positive detection of system folder

### ISSUE THREAD

**Issue by kwvg** [LiveEnhancementSuite/LESforWindows#2]
**Describe the bug**

False-positive detection of system folders, generates dialog box that could spook users

**To Reproduce**
1. Download the portable version of v1.3.2 and create a new folder on the Desktop, then move the portable executable into it
2. Run the executable
3. Desktop directory will be falsely detected as system directory

**Expected behavior**
No error should be exhibited by LES

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Version v1.3.2

**Proposed Solution**

Replace calls to `RegExMatch` with `InStr` at https://github.com/LiveEnhancementSuite/LESforWindows/blob/release%40v1.3.2/LiveEnhancementSuite.ahk#L163

**Comment by Inversil** [comment]
Fixed in https://github.com/LiveEnhancementSuite/LESforWindows/commit/9873df3e28769814bf6c8b0083d9c2e4b956f6dc
