### ISSUE TITLE
Autoadd not working?

### ISSUE THREAD

**Issue by DirkOlten** [LiveEnhancementSuite/LESforWindows#20]
**Describe the bug**
autoadd is set to 1.
I open a plugin in Ableton Live 11. (Documentation says "look up" but that's ambigious)
Nothing changed neither in right-rouble-click-menue nor in menuconfig.ini

**Expected behavior**
Due to a lack of documentation, I expext opening a plugin (adding it to a track) autoadds this to menuconfig.ini and in menue

**Desktop WIN:**
 - OS: Windows 10 Pro 21H1 19043.1466 german
 - Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz   1.61 GHz
 - Ableon Live Lite 11.0.12

**Comment by enoversum** [comment]
@DirkOlten What LES does, aided by the right-click menu you compose, is practically an automated search (look up) in Live's browser and then the press of the Enter key if you have autoadd enabled. Which means, if you configured your menu right and have no syntax errors, it searches for your provided search terms, takes the first result that matches and adds that as a plugin, sample, preset, Live device… whatever you specified. 
There is a documentation that explains the menu and gives examples and config options, also I believe the default menu has some examples written into its file. Unless you completely misunderstood the concept and did something wrong in the process, this should work, but can be limited in Live Lite. I haven't tried it, but Live Lite should still enable you to look for something in the browser and e.g. add a plugin to the track you fired your right-clicks from.
