### ISSUE TITLE
Shortcuts aren't working in Live 11 & LES 1.3.3[Bug]

### ISSUE THREAD

**Issue by Ustik86** [LiveEnhancementSuite/LESforWindows#21]
**Describe the bug**
Hi! I'm using Live and LES on Windows 10 (installed on MacBook Pro early 2013 via bootcamp).

Most of the features of LES work fine, but ALT+C, ALT+X don't. I think maybe it is because of scaling?

The resolution of the screen is 2880x1800 and scaling factor is 200% (default recommended)

**To Reproduce**
1. Hover over track and press ALT+C or ALT+X
2. The menu pops up quickly, but nothing happens, it's like a glitch
3. Nothing happens as expected

**Expected behavior**
Track color change or track should be cleared up

**Screenshots**
![Screenshot 4094](https://user-images.githubusercontent.com/46604771/161357527-9ad1542f-b1c8-4efb-af48-2dbabc8b64a2.jpg)
![Screenshot 4095](https://user-images.githubusercontent.com/46604771/161357528-e84462c1-bd23-4b08-b5e3-e9cd8482f6ba.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - 21H2
![Screenshot 4096](https://user-images.githubusercontent.com/46604771/161357556-69028658-53f5-4034-9aaa-35ba3c6a697c.jpg)

**Additional context**

**Comment by enoversum** [comment]
I already reported Alt + X not working here: https://github.com/LiveEnhancementSuite/LESforWindows/issues/14
Strange that Alt + C doesn't do anything for you, I could successfully use it to colour my tracks in Live 11.

**Comment by Ustik86** [comment]
No it doesn’t, same behavior for both shortcuts. If needed I can make a
screencast to reproduce the bug

**Comment by enoversum** [comment]
Unfortunately, I do believe you, but I am not managing LES, just a really happy fan that occasionally reports bugs as precisely as possible 😊. Just wondering why it doesn't work for you, Alt + C, but for me. I don't think it has anything to do with Windows 10/11, rather maybe some keyboard inconsistency across languages. Still don't know!

**Comment by Ustik86** [comment]
Thanks for the tip!

**Comment by Inversil** [comment]
nah it's actually broken, I'm fixing it when I get the time to get around to it.

**Comment by Ustik86** [comment]
Thanks.
