### ISSUE TITLE
[Feature/bug] the menu query "utility" opens up "cv-utility". Suggestion for search result specification.

### ISSUE THREAD

**Issue by Smopraq** [LiveEnhancementSuite/LESforWindows#22]
Note: This will only apply to users that run the English version of Ableton Suite 11 or have a separate Max 4 Live license.

This is a request from an issue I encounter when trying to add the "Utility" audio effect via the shortcut menu.  The search function, at least on my end, always comes up with the max for live device "CV-Utility" before displaying the "Utility" device.  And therefore adding the wrong devices upon requesting the right name.

It seems to me, correct me if i'm very wrong here, that your menu lookup feature/macro uses the Ableton search function and adds the first entry from the results to the selected channel. There is, as far as I know, no native search attribute like the for example "VST3" addition to only display VST3 plugins in the results that does this for instruments, audio effects etc. 

The actual wanted result for me is always second in the menu, so my suggestion would be to add an optional attribute that  specifies which search entry you want your query to add from the search results when you encounter such anomalies. The syntax could be "#2" for example.

I tried adding the "audio effect" phrase behind the search variable in the configuration, but it made no difference.

Just want to add this non-related piece of information: l absolutely love this little program, it was/is an absolute game changer for me. Keep up the good work.

**Comment by yanjingzhaisun** [comment]
same for reverb, it shows  convolution reverb now.

**Comment by Inversil** [comment]
Yeah it really irks me, but in the release of live 11 ableton removed the option for literal search; or at least... it broke. In the past you could specify "reverb" to get only the reverb device and nothing else; but this no longer works.

the current best workaround I know of, is to save a preset of utility with a slightly different name; and load that up using the LES shortcut menu by specifying the .adv file extension. This is how I personally deal with glue compressor and compressor (a similar problem).

**Comment by Smopraq** [comment]
Nice, that's actually a solution. 👍 

And by you adding the "wontfix" I guess we're done here. Thanks for explaining.
