### ISSUE TITLE
[Bug] Cannot add Key Mapping to Plugin while LES is running (and previous key mapping fails)

### ISSUE THREAD

**Issue by Fasto5** [LiveEnhancementSuite/LESforWindows#23]
**Describe the bug**
I want to be able to add a key mapping to turn 'on/off' a plug in on my master chain, but I cannot do this for a certain key with LES enabled. 
Also - if I disable LES and add the desired mapping, the mapping does not work with LES running. 

I have double checked that the mapping key ( ` ) is not in use by LES and it isn't, so I don't understand this behaviour at all.

**To Reproduce**
With LES running Go to Live's Key Mapping - you cannot map with the ` key (but you CAN map this key with LES disabled)
IF this key has been mapped with LES off (the only way I know how) it does not work when LES is running
If this issue cannot be fixed, or is not an 'issue', then a COMPLETE LIST OF KEYS THAT CANNOT BE MAPPED (OR SHOULD BE AVOIDED) USING LES would be greatly appreciated.

**Expected behavior**
a) Either the ability to add key mapping with LES running, or
b) the ability for key mapping to work once LES is running, or
c) A COMPLETE LIST OF KEYS THAT CANNOT BE MAPPED (OR SHOULD BE AVOIDED) USING LES 

**Desktop (please complete the following information):**
 - OS: W10 (latest updates)
 - LIVE vers 11.1.1
 - Have tried with Laptop's keyboard and also Logitech MX Keys Keyboard. Makes no difference

**Comment by Inversil** [comment]
the key you're experiencing issues with, is the piano roll macro that is a part of LES; it could be found in the documentation under the piano menu information but it was a tad bit easy to miss; so I moved it, updating the documentation website in the process.
That tilde key macro that your keybinds are conflicting with, is actually one of the main things I personally use the macro suite for; so it's worth looking into I think. 

You can move the key this feature mapped to in the settings file, but I don't think it'll be easy to find a better key for it.

I hope that helps! 

https://docs.enhancementsuite.me/pianomacro.html#piano-roll-macro
