### ISSUE TITLE
Submenus not showing up[Bug]

### ISSUE THREAD

**Issue by ThijsvanHees** [LiveEnhancementSuite/LESforWindows#28]
Can't seem to make submenus show-up without having a normal item in the category.

In the example below the submenus are not showing up.

/EQ

//Analog

EQ Eight Analog
EQ Eight Analog

//Digital

EQ Eight
EQ Eight

In the example below they are showing up.

/EQ

Serum
"Serum_x64" vst

//Analog

EQ Eight Analog
EQ Eight Analog

//Digital

EQ Eight
EQ Eight

Is this a user error on my part or a real bug?

With kind regards,

**Comment by HarleySteelX** [comment]
Has anyone found a fix to this? I’m confused I’m having the same problem, yet I see others have submenus setup without the need for a normal item inside them? I have tried everything I can think of.

**Comment by Inversil** [comment]
it's in the documentation that you cannot have submenus without normal items in them. this is an inherent limitation of the program caused by the syntax in autohotkey, the API used to write the program.
