### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ric773** [LiveEnhancementSuite/LESforWindows#29]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS High Sierra 10.13.3 (17D47)]
 - Version [e.g. v9.1]

**Additional context**

**Comment by ric773** [comment]
sorry this was a mistake. didnt mean to post it!

**Comment by Inversil** [comment]
all good!
