### ISSUE TITLE
[Bug] Error: Menu name too long

### ISSUE THREAD

**Issue by Davquak** [LiveEnhancementSuite/LESforWindows#30]
When I change something in the configure menu notepad it works for a minute and then I run into this error when I double press right click: 
Menu name too long.
Line#
869: Menu,categoryname[depth],Add,Array[mathvar],menuitemcount
The current thread will exit

I have to re install LES in order to use the function again

**Comment by Inversil** [comment]
this happens when there's something going very wrong in your menu config file. maybe because there is one line that is being detected as having an item on it, when in reality it does not. Do you have any empty spaces, or special non alphanumeric characters?

**Comment by Inversil** [comment]
please let me know if you run into any other issues. feel free to post the menuconfig contents in here.

EDIT: okay I'm closing this issue for real now because it's been a really long time and I can't really fix this on my end.
