### ISSUE TITLE
[Bug] Can't type uppercase L using right Shift

### ISSUE THREAD

**Issue by snugsound** [LiveEnhancementSuite/LESforWindows#34]
**Describe the bug**
Something with LES is preventing me from typing an uppercase L using the right Shift + L key. Moreover, this key combination results in focus of the current input being lost. The issue appears to be entirely specific to this key combination.

**To Reproduce**
1. Attempt to rename a track or a device to "LES" using the right Shift key
2. Observe that the focus is lost and the rename operation is cancelled 
3. Close LES and observe that the track can be renamed successfully

**Expected behavior**
I should be able to type an upper case L regardless of which Shift key I use. If this is a hotkey, there should be some indication of this in default settings.ini file along with an option to disable it.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 22H2
 - Live 11.3.3 / LES 0.1.3.3

**Additional context**
N/A

**Comment by L0rdVetinari** [comment]
"If this is a hotkey, there should be some indication of this in default settings.ini file along with an option to disable it."

There is. Right shift + L is the shortcut for adding a playlist locator as you can read in the manual: https://docs.enhancementsuite.me/keyboard_shortcuts.html

You can change it to right Alt key.

**Comment by snugsound** [comment]
Ah, thanks, I missed that.
