### ISSUE TITLE
[Bug] Old cursor focus bug

### ISSUE THREAD

**Issue by christianmalek** [LiveEnhancementSuite/LESforWindows#5]
Since the old repository has been archived, I just wanted to quickly reply here that the bug still exists. See https://github.com/Inversil/LESwin/issues/2

Tested with LES 1.3.2 and Ableton 10.1.30

**Comment by Inversil** [comment]
Ah yikes, I've had it a few times myself but only like 2-3 times in the last 6 months, which is not too bad.
Just like last time I'm really puzzled as to why it would happen. Does it happen less often at least like on my end?

**Comment by christianmalek** [comment]
Hey! For me it also happens waay less than the last time. It's not really that annoying. I just wanted to let you know it still exists. :)

**Comment by Inversil** [comment]
OK! that's good to know. 
Even though I managed to make it super rare, I still have no idea why it happens at all. 
I'll just leave the issue open in case someone figures it out

**Comment by Inversil** [comment]
it might've had to do this with other issue (#11) I haven't experienced this problem in a long time; so I think it's fixed! feel free to reopen or make a new issue if you encounter it again
