### ISSUE TITLE
Quickmarker code not working in Live 11

### ISSUE THREAD

**Issue by spice3d** [LiveEnhancementSuite/LESforWindows#8]
1. quickmarker no longer works in Live 11. Live's Create menu has been changed. There is a new item before Add Locator *and* they added divider lines. Apparently, AutoHotKey counts divider lines as menu items. As such, for Live 11, Add Locator is menu item 20.

2. Also, apparently there has always been a bug in the code. The variable in the InStr commands should be wintitleoutput not title. Prolly never worked in Live 9. LOL

Here's my suggestion for the routine. Works in 10 and 11. I don't anything else to test on.

quickmarker:
WinGetActiveTitle, wintitleoutput
if !(InStr(wintitleoutput, "Live 9", CaseSensitive := false) = 0){
WinMenuSelectItem,,, 3&, 13&
}
Else if !(InStr(wintitleoutput, "Live 10", CaseSensitive := false) = 0){
WinMenuSelectItem,,, 3&, 14&
}
Else {
WinMenuSelectItem,,, 3&, 20&
}
return

**Comment by Inversil** [comment]
oh yeah I noticed this too! I fixed it just a few minutes ago just by doing 

`WinmenuSelectItem,,, Create, Add Locator`

if you make a pull request next time I get notified by mail and I can add it with the push of a button!

**Comment by spice3d** [comment]
Thanks. On a side note, I was looking thru the code (was thinking about adding icons to indicate favorites) and was laughing at the remarks. Hilarious.

**Comment by Inversil** [comment]
I just realized why I did it the other way initially; it makes the shortcut language independent. This approach only works if you run ableton live in English.

I will try and see if I can retroactively implement your code since it’s actually better and not worse

**Comment by spice3d** [comment]
Yup, makes sense.

**Comment by Arjasonjai** [comment]
It is still not working for me

**Comment by Inversil** [comment]
That’s because I haven’t released an update to address this issue yet.
The current implementation works if live’s language is in english, but it won’t work if it’s not.

**Comment by Inversil** [comment]
just fixed it! will make an update soon
can clone the git if you can't wait for me to update the website etc
https://github.com/LiveEnhancementSuite/LESforWindows/commit/10b9dece6ef6e5e779c5591bd2855cdf312b8c33
